//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSServiceApi
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://smslive247.com/bulksms/service", ConfigurationName="SMSServiceApi.ISMSSiteAdmin")]
    public interface ISMSSiteAdmin
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/NewSiteUser", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/NewSiteUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SMSServiceApi.ResponseInfo NewSiteUser(string site_token, SMSServiceApi.SMSSiteUserInfo User);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/NewSiteUser", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/NewSiteUserResponse")]
        System.Threading.Tasks.Task<SMSServiceApi.ResponseInfo> NewSiteUserAsync(string site_token, SMSServiceApi.SMSSiteUserInfo User);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/UpdateSiteUser", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/UpdateSiteUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SMSServiceApi.ResponseInfo UpdateSiteUser(string site_token, SMSServiceApi.SMSSiteUserInfo User);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/UpdateSiteUser", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/UpdateSiteUserResponse")]
        System.Threading.Tasks.Task<SMSServiceApi.ResponseInfo> UpdateSiteUserAsync(string site_token, SMSServiceApi.SMSSiteUserInfo User);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/DeleteSiteUser", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/DeleteSiteUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SMSServiceApi.ResponseInfo DeleteSiteUser(string site_token, string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/DeleteSiteUser", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/DeleteSiteUserResponse")]
        System.Threading.Tasks.Task<SMSServiceApi.ResponseInfo> DeleteSiteUserAsync(string site_token, string Username);
        
        // CODEGEN: Parameter 'GetAllSiteUsersResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/GetAllSiteUsers", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/GetAllSiteUsersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SMSServiceApi.GetAllSiteUsersResponse GetAllSiteUsers(SMSServiceApi.GetAllSiteUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/GetAllSiteUsers", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/GetAllSiteUsersResponse")]
        System.Threading.Tasks.Task<SMSServiceApi.GetAllSiteUsersResponse> GetAllSiteUsersAsync(SMSServiceApi.GetAllSiteUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/FlashSiteUser", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/FlashSiteUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SMSServiceApi.ResponseInfo FlashSiteUser(string site_token, string RecieverName, int SMS_Count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/FlashSiteUser", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/FlashSiteUserResponse")]
        System.Threading.Tasks.Task<SMSServiceApi.ResponseInfo> FlashSiteUserAsync(string site_token, string RecieverName, int SMS_Count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/Login", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/LoginResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SMSServiceApi.ResponseInfo Login(string site_id, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/Login", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/LoginResponse")]
        System.Threading.Tasks.Task<SMSServiceApi.ResponseInfo> LoginAsync(string site_id, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/ChangePwd", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/ChangePwdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SMSServiceApi.ResponseInfo ChangePwd(string site_token, string OldPassword, string NewPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/ChangePwd", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/ChangePwdResponse")]
        System.Threading.Tasks.Task<SMSServiceApi.ResponseInfo> ChangePwdAsync(string site_token, string OldPassword, string NewPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/Recharge", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/RechargeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SMSServiceApi.ResponseInfo Recharge(string site_token, string str16DigitCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/Recharge", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/RechargeResponse")]
        System.Threading.Tasks.Task<SMSServiceApi.ResponseInfo> RechargeAsync(string site_token, string str16DigitCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/UpdateAccountInfo", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/UpdateAccountInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SMSServiceApi.ResponseInfo UpdateAccountInfo(string site_token, SMSServiceApi.SMSSiteInfo NewInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/UpdateAccountInfo", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/UpdateAccountInfoResponse")]
        System.Threading.Tasks.Task<SMSServiceApi.ResponseInfo> UpdateAccountInfoAsync(string site_token, SMSServiceApi.SMSSiteInfo NewInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/GetAccountInfo", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/GetAccountInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SMSServiceApi.SMSSiteInfo GetAccountInfo(string site_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/GetAccountInfo", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/GetAccountInfoResponse")]
        System.Threading.Tasks.Task<SMSServiceApi.SMSSiteInfo> GetAccountInfoAsync(string site_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/SendSMS", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/SendSMSResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SMSServiceApi.ResponseInfo SendSMS(string site_token, SMSServiceApi.MessageInfo NewSMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/SendSMS", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/SendSMSResponse")]
        System.Threading.Tasks.Task<SMSServiceApi.ResponseInfo> SendSMSAsync(string site_token, SMSServiceApi.MessageInfo NewSMS);
        
        // CODEGEN: Parameter 'GetMessagesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/GetMessages", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/GetMessagesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SMSServiceApi.GetMessagesResponse GetMessages(SMSServiceApi.GetMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/GetMessages", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/GetMessagesResponse")]
        System.Threading.Tasks.Task<SMSServiceApi.GetMessagesResponse> GetMessagesAsync(SMSServiceApi.GetMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/DeleteMessage", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/DeleteMessageResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SMSServiceApi.ResponseInfo DeleteMessage(string site_token, string MessageID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/DeleteMessage", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/DeleteMessageResponse")]
        System.Threading.Tasks.Task<SMSServiceApi.ResponseInfo> DeleteMessageAsync(string site_token, string MessageID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/InsertContact", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/InsertContactResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SMSServiceApi.ResponseInfo InsertContact(string site_token, SMSServiceApi.ContactInfo myContact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/InsertContact", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/InsertContactResponse")]
        System.Threading.Tasks.Task<SMSServiceApi.ResponseInfo> InsertContactAsync(string site_token, SMSServiceApi.ContactInfo myContact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/UpdateContact", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/UpdateContactResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SMSServiceApi.ResponseInfo UpdateContact(string site_token, SMSServiceApi.ContactInfo myContact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/UpdateContact", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/UpdateContactResponse")]
        System.Threading.Tasks.Task<SMSServiceApi.ResponseInfo> UpdateContactAsync(string site_token, SMSServiceApi.ContactInfo myContact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/DeleteContact", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/DeleteContactResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SMSServiceApi.ResponseInfo DeleteContact(string site_token, string MobileNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/DeleteContact", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/DeleteContactResponse")]
        System.Threading.Tasks.Task<SMSServiceApi.ResponseInfo> DeleteContactAsync(string site_token, string MobileNo);
        
        // CODEGEN: Parameter 'GetContactsResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/GetContacts", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/GetContactsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SMSServiceApi.GetContactsResponse GetContacts(SMSServiceApi.GetContactsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smslive247.com/bulksms/service/GetContacts", ReplyAction="http://smslive247.com/bulksms/service/ISMSSiteAdmin/GetContactsResponse")]
        System.Threading.Tasks.Task<SMSServiceApi.GetContactsResponse> GetContactsAsync(SMSServiceApi.GetContactsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smslive247.com/bulksms/service")]
    public partial class SMSSiteUserInfo
    {
        
        private string owner_tx_idField;
        
        private System.DateTime dateCreatedField;
        
        private string ws_tx_idField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string streetField;
        
        private string cityField;
        
        private string stateField;
        
        private string countryField;
        
        private string emailField;
        
        private string phoneField;
        
        private long cBalanceField;
        
        private UserInfo_settings userSettingsField;
        
        private int activeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string owner_tx_id
        {
            get
            {
                return this.owner_tx_idField;
            }
            set
            {
                this.owner_tx_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime DateCreated
        {
            get
            {
                return this.dateCreatedField;
            }
            set
            {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ws_tx_id
        {
            get
            {
                return this.ws_tx_idField;
            }
            set
            {
                this.ws_tx_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public long CBalance
        {
            get
            {
                return this.cBalanceField;
            }
            set
            {
                this.cBalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public UserInfo_settings UserSettings
        {
            get
            {
                return this.userSettingsField;
            }
            set
            {
                this.userSettingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int Active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smslive247.com/bulksms/service")]
    public partial class UserInfo_settings
    {
        
        private string senderIDField;
        
        private string signatureField;
        
        private string errorEmailField;
        
        private int useSignatureField;
        
        private int timeZoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SenderID
        {
            get
            {
                return this.senderIDField;
            }
            set
            {
                this.senderIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorEmail
        {
            get
            {
                return this.errorEmailField;
            }
            set
            {
                this.errorEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int UseSignature
        {
            get
            {
                return this.useSignatureField;
            }
            set
            {
                this.useSignatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int TimeZone
        {
            get
            {
                return this.timeZoneField;
            }
            set
            {
                this.timeZoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smslive247.com/bulksms/service")]
    public partial class ContactInfo
    {
        
        private string aliasField;
        
        private string emailField;
        
        private string mobileField;
        
        private string[] groupsField;
        
        private string lastNameField;
        
        private string firstNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Alias
        {
            get
            {
                return this.aliasField;
            }
            set
            {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Mobile
        {
            get
            {
                return this.mobileField;
            }
            set
            {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public string[] Groups
        {
            get
            {
                return this.groupsField;
            }
            set
            {
                this.groupsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smslive247.com/bulksms/service")]
    public partial class SentMessageInfo
    {
        
        private System.DateTime sendEndDateField;
        
        private System.DateTime sendStartDateField;
        
        private long totalSmsField;
        
        private long totalSentField;
        
        private long totalFailedField;
        
        private MessageInfo shortMessageField;
        
        private SendStatusEnum sendStatusField;
        
        private string sendStatusStrField;
        
        private string ownerEmailField;
        
        private string ws_tx_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime SendEndDate
        {
            get
            {
                return this.sendEndDateField;
            }
            set
            {
                this.sendEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime SendStartDate
        {
            get
            {
                return this.sendStartDateField;
            }
            set
            {
                this.sendStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long TotalSms
        {
            get
            {
                return this.totalSmsField;
            }
            set
            {
                this.totalSmsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long TotalSent
        {
            get
            {
                return this.totalSentField;
            }
            set
            {
                this.totalSentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long TotalFailed
        {
            get
            {
                return this.totalFailedField;
            }
            set
            {
                this.totalFailedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public MessageInfo ShortMessage
        {
            get
            {
                return this.shortMessageField;
            }
            set
            {
                this.shortMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public SendStatusEnum SendStatus
        {
            get
            {
                return this.sendStatusField;
            }
            set
            {
                this.sendStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string SendStatusStr
        {
            get
            {
                return this.sendStatusStrField;
            }
            set
            {
                this.sendStatusStrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string OwnerEmail
        {
            get
            {
                return this.ownerEmailField;
            }
            set
            {
                this.ownerEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ws_tx_id
        {
            get
            {
                return this.ws_tx_idField;
            }
            set
            {
                this.ws_tx_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smslive247.com/bulksms/service")]
    public partial class MessageInfo
    {
        
        private string messageField;
        
        private long messageIDField;
        
        private SMSTypeEnum messageTypeField;
        
        private MessageFolder messageFolderField;
        
        private string callBackField;
        
        private string[] destinationField;
        
        private string deliveryEmailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long MessageID
        {
            get
            {
                return this.messageIDField;
            }
            set
            {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public SMSTypeEnum MessageType
        {
            get
            {
                return this.messageTypeField;
            }
            set
            {
                this.messageTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public MessageFolder MessageFolder
        {
            get
            {
                return this.messageFolderField;
            }
            set
            {
                this.messageFolderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CallBack
        {
            get
            {
                return this.callBackField;
            }
            set
            {
                this.callBackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public string[] Destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DeliveryEmail
        {
            get
            {
                return this.deliveryEmailField;
            }
            set
            {
                this.deliveryEmailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smslive247.com/bulksms/service")]
    public enum SMSTypeEnum
    {
        
        /// <remarks/>
        TEXT,
        
        /// <remarks/>
        FLASH,
        
        /// <remarks/>
        OLOGO,
        
        /// <remarks/>
        RTONE,
        
        /// <remarks/>
        VCARD,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smslive247.com/bulksms/service")]
    public enum MessageFolder
    {
        
        /// <remarks/>
        SENT_FOLDER,
        
        /// <remarks/>
        SAVED_FOLDER,
        
        /// <remarks/>
        BULK_SENT_FOLDER,
        
        /// <remarks/>
        BULK_SAVED_FOLDER,
        
        /// <remarks/>
        WEBSMS_SENT_FOLDER,
        
        /// <remarks/>
        CUSTOM_SENT_FOLDER,
        
        /// <remarks/>
        BULK_ISSENDING_FOLDER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smslive247.com/bulksms/service")]
    public enum SendStatusEnum
    {
        
        /// <remarks/>
        SENT,
        
        /// <remarks/>
        SENDING,
        
        /// <remarks/>
        PAUSED,
        
        /// <remarks/>
        STOPPED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smslive247.com/bulksms/service")]
    public partial class SMSSiteInfo
    {
        
        private string ws_tx_idField;
        
        private System.DateTime dateCreatedField;
        
        private string ownerEmailField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string emailField;
        
        private string prefixField;
        
        private string suffixField;
        
        private string sentUrlField;
        
        private string errorUrlField;
        
        private string sentEmailField;
        
        private string errorEmailField;
        
        private string callbackField;
        
        private bool callbackActiveField;
        
        private System.DateTime callbackExpiryField;
        
        private long cBalanceField;
        
        private int activeField;
        
        private int totalUsersField;
        
        private string remarksField;
        
        private string tag1Field;
        
        private string tag2Field;
        
        private string tag3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ws_tx_id
        {
            get
            {
                return this.ws_tx_idField;
            }
            set
            {
                this.ws_tx_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime DateCreated
        {
            get
            {
                return this.dateCreatedField;
            }
            set
            {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OwnerEmail
        {
            get
            {
                return this.ownerEmailField;
            }
            set
            {
                this.ownerEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Prefix
        {
            get
            {
                return this.prefixField;
            }
            set
            {
                this.prefixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Suffix
        {
            get
            {
                return this.suffixField;
            }
            set
            {
                this.suffixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string SentUrl
        {
            get
            {
                return this.sentUrlField;
            }
            set
            {
                this.sentUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ErrorUrl
        {
            get
            {
                return this.errorUrlField;
            }
            set
            {
                this.errorUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string SentEmail
        {
            get
            {
                return this.sentEmailField;
            }
            set
            {
                this.sentEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ErrorEmail
        {
            get
            {
                return this.errorEmailField;
            }
            set
            {
                this.errorEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Callback
        {
            get
            {
                return this.callbackField;
            }
            set
            {
                this.callbackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool CallbackActive
        {
            get
            {
                return this.callbackActiveField;
            }
            set
            {
                this.callbackActiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public System.DateTime CallbackExpiry
        {
            get
            {
                return this.callbackExpiryField;
            }
            set
            {
                this.callbackExpiryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public long CBalance
        {
            get
            {
                return this.cBalanceField;
            }
            set
            {
                this.cBalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int Active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int TotalUsers
        {
            get
            {
                return this.totalUsersField;
            }
            set
            {
                this.totalUsersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Remarks
        {
            get
            {
                return this.remarksField;
            }
            set
            {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Tag1
        {
            get
            {
                return this.tag1Field;
            }
            set
            {
                this.tag1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Tag2
        {
            get
            {
                return this.tag2Field;
            }
            set
            {
                this.tag2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Tag3
        {
            get
            {
                return this.tag3Field;
            }
            set
            {
                this.tag3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smslive247.com/bulksms/service")]
    public partial class ResponseInfo
    {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        private string extraMessageField;
        
        private int totalSuccessField;
        
        private int totalFailureField;
        
        private int totalChargedField;
        
        private long currentBalanceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ExtraMessage
        {
            get
            {
                return this.extraMessageField;
            }
            set
            {
                this.extraMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int TotalSuccess
        {
            get
            {
                return this.totalSuccessField;
            }
            set
            {
                this.totalSuccessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int TotalFailure
        {
            get
            {
                return this.totalFailureField;
            }
            set
            {
                this.totalFailureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int TotalCharged
        {
            get
            {
                return this.totalChargedField;
            }
            set
            {
                this.totalChargedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long CurrentBalance
        {
            get
            {
                return this.currentBalanceField;
            }
            set
            {
                this.currentBalanceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllSiteUsers", WrapperNamespace="http://smslive247.com/bulksms/service", IsWrapped=true)]
    public partial class GetAllSiteUsersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smslive247.com/bulksms/service", Order=0)]
        public string site_token;
        
        public GetAllSiteUsersRequest()
        {
        }
        
        public GetAllSiteUsersRequest(string site_token)
        {
            this.site_token = site_token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllSiteUsersResponse", WrapperNamespace="http://smslive247.com/bulksms/service", IsWrapped=true)]
    public partial class GetAllSiteUsersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smslive247.com/bulksms/service", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SMSServiceApi.SMSSiteUserInfo[] GetAllSiteUsersResult;
        
        public GetAllSiteUsersResponse()
        {
        }
        
        public GetAllSiteUsersResponse(SMSServiceApi.SMSSiteUserInfo[] GetAllSiteUsersResult)
        {
            this.GetAllSiteUsersResult = GetAllSiteUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessages", WrapperNamespace="http://smslive247.com/bulksms/service", IsWrapped=true)]
    public partial class GetMessagesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smslive247.com/bulksms/service", Order=0)]
        public string site_token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smslive247.com/bulksms/service", Order=1)]
        public System.DateTime from_date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smslive247.com/bulksms/service", Order=2)]
        public System.DateTime to_date;
        
        public GetMessagesRequest()
        {
        }
        
        public GetMessagesRequest(string site_token, System.DateTime from_date, System.DateTime to_date)
        {
            this.site_token = site_token;
            this.from_date = from_date;
            this.to_date = to_date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessagesResponse", WrapperNamespace="http://smslive247.com/bulksms/service", IsWrapped=true)]
    public partial class GetMessagesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smslive247.com/bulksms/service", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SMSServiceApi.SentMessageInfo[] GetMessagesResult;
        
        public GetMessagesResponse()
        {
        }
        
        public GetMessagesResponse(SMSServiceApi.SentMessageInfo[] GetMessagesResult)
        {
            this.GetMessagesResult = GetMessagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetContacts", WrapperNamespace="http://smslive247.com/bulksms/service", IsWrapped=true)]
    public partial class GetContactsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smslive247.com/bulksms/service", Order=0)]
        public string site_token;
        
        public GetContactsRequest()
        {
        }
        
        public GetContactsRequest(string site_token)
        {
            this.site_token = site_token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetContactsResponse", WrapperNamespace="http://smslive247.com/bulksms/service", IsWrapped=true)]
    public partial class GetContactsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smslive247.com/bulksms/service", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SMSServiceApi.ContactInfo[] GetContactsResult;
        
        public GetContactsResponse()
        {
        }
        
        public GetContactsResponse(SMSServiceApi.ContactInfo[] GetContactsResult)
        {
            this.GetContactsResult = GetContactsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISMSSiteAdminChannel : SMSServiceApi.ISMSSiteAdmin, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSSiteAdminClient : System.ServiceModel.ClientBase<SMSServiceApi.ISMSSiteAdmin>, SMSServiceApi.ISMSSiteAdmin
    {
        
        public SMSSiteAdminClient()
        {
        }
        
        public SMSSiteAdminClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public SMSSiteAdminClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SMSSiteAdminClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public SMSSiteAdminClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public SMSServiceApi.ResponseInfo NewSiteUser(string site_token, SMSServiceApi.SMSSiteUserInfo User)
        {
            return base.Channel.NewSiteUser(site_token, User);
        }
        
        public System.Threading.Tasks.Task<SMSServiceApi.ResponseInfo> NewSiteUserAsync(string site_token, SMSServiceApi.SMSSiteUserInfo User)
        {
            return base.Channel.NewSiteUserAsync(site_token, User);
        }
        
        public SMSServiceApi.ResponseInfo UpdateSiteUser(string site_token, SMSServiceApi.SMSSiteUserInfo User)
        {
            return base.Channel.UpdateSiteUser(site_token, User);
        }
        
        public System.Threading.Tasks.Task<SMSServiceApi.ResponseInfo> UpdateSiteUserAsync(string site_token, SMSServiceApi.SMSSiteUserInfo User)
        {
            return base.Channel.UpdateSiteUserAsync(site_token, User);
        }
        
        public SMSServiceApi.ResponseInfo DeleteSiteUser(string site_token, string Username)
        {
            return base.Channel.DeleteSiteUser(site_token, Username);
        }
        
        public System.Threading.Tasks.Task<SMSServiceApi.ResponseInfo> DeleteSiteUserAsync(string site_token, string Username)
        {
            return base.Channel.DeleteSiteUserAsync(site_token, Username);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMSServiceApi.GetAllSiteUsersResponse SMSServiceApi.ISMSSiteAdmin.GetAllSiteUsers(SMSServiceApi.GetAllSiteUsersRequest request)
        {
            return base.Channel.GetAllSiteUsers(request);
        }
        
        public SMSServiceApi.SMSSiteUserInfo[] GetAllSiteUsers(string site_token)
        {
            SMSServiceApi.GetAllSiteUsersRequest inValue = new SMSServiceApi.GetAllSiteUsersRequest();
            inValue.site_token = site_token;
            SMSServiceApi.GetAllSiteUsersResponse retVal = ((SMSServiceApi.ISMSSiteAdmin)(this)).GetAllSiteUsers(inValue);
            return retVal.GetAllSiteUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMSServiceApi.GetAllSiteUsersResponse> SMSServiceApi.ISMSSiteAdmin.GetAllSiteUsersAsync(SMSServiceApi.GetAllSiteUsersRequest request)
        {
            return base.Channel.GetAllSiteUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSServiceApi.GetAllSiteUsersResponse> GetAllSiteUsersAsync(string site_token)
        {
            SMSServiceApi.GetAllSiteUsersRequest inValue = new SMSServiceApi.GetAllSiteUsersRequest();
            inValue.site_token = site_token;
            return ((SMSServiceApi.ISMSSiteAdmin)(this)).GetAllSiteUsersAsync(inValue);
        }
        
        public SMSServiceApi.ResponseInfo FlashSiteUser(string site_token, string RecieverName, int SMS_Count)
        {
            return base.Channel.FlashSiteUser(site_token, RecieverName, SMS_Count);
        }
        
        public System.Threading.Tasks.Task<SMSServiceApi.ResponseInfo> FlashSiteUserAsync(string site_token, string RecieverName, int SMS_Count)
        {
            return base.Channel.FlashSiteUserAsync(site_token, RecieverName, SMS_Count);
        }
        
        public SMSServiceApi.ResponseInfo Login(string site_id, string Password)
        {
            return base.Channel.Login(site_id, Password);
        }
        
        public System.Threading.Tasks.Task<SMSServiceApi.ResponseInfo> LoginAsync(string site_id, string Password)
        {
            return base.Channel.LoginAsync(site_id, Password);
        }
        
        public SMSServiceApi.ResponseInfo ChangePwd(string site_token, string OldPassword, string NewPassword)
        {
            return base.Channel.ChangePwd(site_token, OldPassword, NewPassword);
        }
        
        public System.Threading.Tasks.Task<SMSServiceApi.ResponseInfo> ChangePwdAsync(string site_token, string OldPassword, string NewPassword)
        {
            return base.Channel.ChangePwdAsync(site_token, OldPassword, NewPassword);
        }
        
        public SMSServiceApi.ResponseInfo Recharge(string site_token, string str16DigitCode)
        {
            return base.Channel.Recharge(site_token, str16DigitCode);
        }
        
        public System.Threading.Tasks.Task<SMSServiceApi.ResponseInfo> RechargeAsync(string site_token, string str16DigitCode)
        {
            return base.Channel.RechargeAsync(site_token, str16DigitCode);
        }
        
        public SMSServiceApi.ResponseInfo UpdateAccountInfo(string site_token, SMSServiceApi.SMSSiteInfo NewInfo)
        {
            return base.Channel.UpdateAccountInfo(site_token, NewInfo);
        }
        
        public System.Threading.Tasks.Task<SMSServiceApi.ResponseInfo> UpdateAccountInfoAsync(string site_token, SMSServiceApi.SMSSiteInfo NewInfo)
        {
            return base.Channel.UpdateAccountInfoAsync(site_token, NewInfo);
        }
        
        public SMSServiceApi.SMSSiteInfo GetAccountInfo(string site_token)
        {
            return base.Channel.GetAccountInfo(site_token);
        }
        
        public System.Threading.Tasks.Task<SMSServiceApi.SMSSiteInfo> GetAccountInfoAsync(string site_token)
        {
            return base.Channel.GetAccountInfoAsync(site_token);
        }
        
        public SMSServiceApi.ResponseInfo SendSMS(string site_token, SMSServiceApi.MessageInfo NewSMS)
        {
            return base.Channel.SendSMS(site_token, NewSMS);
        }
        
        public System.Threading.Tasks.Task<SMSServiceApi.ResponseInfo> SendSMSAsync(string site_token, SMSServiceApi.MessageInfo NewSMS)
        {
            return base.Channel.SendSMSAsync(site_token, NewSMS);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMSServiceApi.GetMessagesResponse SMSServiceApi.ISMSSiteAdmin.GetMessages(SMSServiceApi.GetMessagesRequest request)
        {
            return base.Channel.GetMessages(request);
        }
        
        public SMSServiceApi.SentMessageInfo[] GetMessages(string site_token, System.DateTime from_date, System.DateTime to_date)
        {
            SMSServiceApi.GetMessagesRequest inValue = new SMSServiceApi.GetMessagesRequest();
            inValue.site_token = site_token;
            inValue.from_date = from_date;
            inValue.to_date = to_date;
            SMSServiceApi.GetMessagesResponse retVal = ((SMSServiceApi.ISMSSiteAdmin)(this)).GetMessages(inValue);
            return retVal.GetMessagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMSServiceApi.GetMessagesResponse> SMSServiceApi.ISMSSiteAdmin.GetMessagesAsync(SMSServiceApi.GetMessagesRequest request)
        {
            return base.Channel.GetMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSServiceApi.GetMessagesResponse> GetMessagesAsync(string site_token, System.DateTime from_date, System.DateTime to_date)
        {
            SMSServiceApi.GetMessagesRequest inValue = new SMSServiceApi.GetMessagesRequest();
            inValue.site_token = site_token;
            inValue.from_date = from_date;
            inValue.to_date = to_date;
            return ((SMSServiceApi.ISMSSiteAdmin)(this)).GetMessagesAsync(inValue);
        }
        
        public SMSServiceApi.ResponseInfo DeleteMessage(string site_token, string MessageID)
        {
            return base.Channel.DeleteMessage(site_token, MessageID);
        }
        
        public System.Threading.Tasks.Task<SMSServiceApi.ResponseInfo> DeleteMessageAsync(string site_token, string MessageID)
        {
            return base.Channel.DeleteMessageAsync(site_token, MessageID);
        }
        
        public SMSServiceApi.ResponseInfo InsertContact(string site_token, SMSServiceApi.ContactInfo myContact)
        {
            return base.Channel.InsertContact(site_token, myContact);
        }
        
        public System.Threading.Tasks.Task<SMSServiceApi.ResponseInfo> InsertContactAsync(string site_token, SMSServiceApi.ContactInfo myContact)
        {
            return base.Channel.InsertContactAsync(site_token, myContact);
        }
        
        public SMSServiceApi.ResponseInfo UpdateContact(string site_token, SMSServiceApi.ContactInfo myContact)
        {
            return base.Channel.UpdateContact(site_token, myContact);
        }
        
        public System.Threading.Tasks.Task<SMSServiceApi.ResponseInfo> UpdateContactAsync(string site_token, SMSServiceApi.ContactInfo myContact)
        {
            return base.Channel.UpdateContactAsync(site_token, myContact);
        }
        
        public SMSServiceApi.ResponseInfo DeleteContact(string site_token, string MobileNo)
        {
            return base.Channel.DeleteContact(site_token, MobileNo);
        }
        
        public System.Threading.Tasks.Task<SMSServiceApi.ResponseInfo> DeleteContactAsync(string site_token, string MobileNo)
        {
            return base.Channel.DeleteContactAsync(site_token, MobileNo);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMSServiceApi.GetContactsResponse SMSServiceApi.ISMSSiteAdmin.GetContacts(SMSServiceApi.GetContactsRequest request)
        {
            return base.Channel.GetContacts(request);
        }
        
        public SMSServiceApi.ContactInfo[] GetContacts(string site_token)
        {
            SMSServiceApi.GetContactsRequest inValue = new SMSServiceApi.GetContactsRequest();
            inValue.site_token = site_token;
            SMSServiceApi.GetContactsResponse retVal = ((SMSServiceApi.ISMSSiteAdmin)(this)).GetContacts(inValue);
            return retVal.GetContactsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMSServiceApi.GetContactsResponse> SMSServiceApi.ISMSSiteAdmin.GetContactsAsync(SMSServiceApi.GetContactsRequest request)
        {
            return base.Channel.GetContactsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMSServiceApi.GetContactsResponse> GetContactsAsync(string site_token)
        {
            SMSServiceApi.GetContactsRequest inValue = new SMSServiceApi.GetContactsRequest();
            inValue.site_token = site_token;
            return ((SMSServiceApi.ISMSSiteAdmin)(this)).GetContactsAsync(inValue);
        }
    }
}
